//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill_Import()
        {
            this.Detail_Bill_Import = new HashSet<Detail_Bill_Import>();
        }
    
        public int Bill_Import_id { get; set; }
        public int NXB_id { get; set; }
        public double Total { get; set; }
        public string Deliver { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual NXB NXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Bill_Import> Detail_Bill_Import { get; set; }
    }
}
