//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Detail_Bill_Import = new HashSet<Detail_Bill_Import>();
            this.Detail_Bill_Export = new HashSet<Detail_Bill_Export>();
            this.Detail_Report_Agency = new HashSet<Detail_Report_Agency>();
            this.Inventory_Book = new HashSet<Inventory_Book>();
            this.Inventory_Agency = new HashSet<Inventory_Agency>();
        }
    
        public int Book_id { get; set; }
        public string Book_name { get; set; }
        public string Author { get; set; }
        public int Field_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost_Export { get; set; }
        public Nullable<int> NXB_id { get; set; }
        public string image { get; set; }
        public Nullable<double> Cost_Import { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual NXB NXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Bill_Import> Detail_Bill_Import { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Bill_Export> Detail_Bill_Export { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Report_Agency> Detail_Report_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Book> Inventory_Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Agency> Inventory_Agency { get; set; }
    }
}
