//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt_Agency
    {
        public int id { get; set; }
        public int Agency_id { get; set; }
        public double debt { get; set; }
        public double repay { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
