//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Report_Agency
    {
        public int id { get; set; }
        public int Report_id { get; set; }
        public int Book_id { get; set; }
        public int quantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Report_Agency Report_Agency { get; set; }
    }
}
