//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NXB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NXB()
        {
            this.Bill_Import = new HashSet<Bill_Import>();
            this.Books = new HashSet<Book>();
            this.Debt_NXB = new HashSet<Debt_NXB>();
            this.Report_NXB = new HashSet<Report_NXB>();
        }
        
        public int NXB_id { get; set; }
        [Required(ErrorMessage = "Thiếu tên NXB")]
        public string NXB_name { get; set; }
        [Required(ErrorMessage = "Thiếu địa chỉ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Thiếu số tài khoản")]
        public string AcountNumber { get; set; }
        [Required(ErrorMessage = "Thiếu số điện thoại")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Thiếu email")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Import> Bill_Import { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debt_NXB> Debt_NXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_NXB> Report_NXB { get; set; }
    }
}
