//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhatHanhSachEntities : DbContext
    {
        public PhatHanhSachEntities()
            : base("name=PhatHanhSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<Bill_Export> Bill_Export { get; set; }
        public virtual DbSet<Bill_Import> Bill_Import { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Debt_Agency> Debt_Agency { get; set; }
        public virtual DbSet<Debt_NXB> Debt_NXB { get; set; }
        public virtual DbSet<Detail_Bill_Export> Detail_Bill_Export { get; set; }
        public virtual DbSet<Detail_Bill_Import> Detail_Bill_Import { get; set; }
        public virtual DbSet<Detail_Report_Agency> Detail_Report_Agency { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Inventory_Agency> Inventory_Agency { get; set; }
        public virtual DbSet<Inventory_Book> Inventory_Book { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<Report_Agency> Report_Agency { get; set; }
        public virtual DbSet<Report_NXB> Report_NXB { get; set; }
    }
}
