//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_NXB
    {
        public int Report_id { get; set; }
        public int NXB_id { get; set; }
        public double total { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int status { get; set; }
    
        public virtual NXB NXB { get; set; }
    }
}
