//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_Agency()
        {
            this.Detail_Report_Agency = new HashSet<Detail_Report_Agency>();
        }
    
        public int Report_id { get; set; }
        public Nullable<int> Agency_id { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Report_Agency> Detail_Report_Agency { get; set; }
    }
}
